### ISSUE TITLE
Hosting of RPMs & DEBs

### ISSUE THREAD

**Issue by pradeepchhetri** [riemann/riemann#718] opened 2016-09-06 16:59 UTC
Currently RPMs & DEBs are being hosted at https://aphyr.com

I have some experience in hosting YUM & DEB repositories via packagecloud (https://packagecloud.io). I think they are free for open-source projects.

I would like to know if you see any value in migrating to packagecloud. 

Thanks !!

**Comment by jamtur01** [comment] 2016-09-10 23:56
In the short term I've added the packages to a release here:

https://github.com/riemann/riemann/releases/tag/0.2.11

**Comment by jamtur01** [comment] 2016-09-10 23:57
I think we might start with GH. Closing as duplicate of #716

**Closed by jamtur01** 2016-09-10 23:57 UTC
